name: deploy mkdocs

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: fortierq/add-binder-link-action@v1

      - run: |
          pip install mkdocs-material scipy ipython_genutils
          mkdir -p docs
          TMP_DIR=$(mktemp -d)
          
          DIR=$(pwd)
          git clone "https://fortierq:${{ secrets.API_TOKEN_GITHUB }}@github.com/fortierq/mkdocs-jupyter.git" "$TMP_DIR/mkdocs-jupyter"
          cd $TMP_DIR/mkdocs-jupyter/js
          npm install && npm run build
          cd ../..
          pip install ./mkdocs-jupyter/
          cd $DIR
          
          mv .git $TMP_DIR
          mv mkdocs.yml $TMP_DIR
          mv overrides $TMP_DIR
          mv * docs/ || true
          mv $TMP_DIR/mkdocs.yml .
          mv $TMP_DIR/.git .
          mv $TMP_DIR/overrides .

          cd docs
          for file in $(find . -type f -name "*.pdf"); do
            fit=FitH
            if [[ $file == td* ]] || [[ $file == TD* ]];
            then
              fit=FitH
            fi
            echo "<iframe src=../$(basename $file)#view=$fit height=800 width=1200></iframe>" > ${file%.*}.md
          done
          cd ..

          mkdocs gh-deploy --force
